name: Update Reddit Data


on:
  schedule:
    - cron: "0 0 1 * *"


jobs: 
  update-data:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Install dependencies
      run: |
        pip install praw pandas

    
    - name: Run the data update script
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      run: |
        python update_reddit_data.py


    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add reddit_data.csv
        git commit -m "Updated Reddit data for the last month"
        git push