name: Update Reddit Data


on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs: 
  update-data:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'


    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    
    - name: Run the data update script
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
      run: |
        python build_df.py

    - name: Run the generate index script
      run: |
        python generate_index.py


    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add data/reddit_data.csv data/faiss_index.index    
        git commit -m "Updated Reddit data for the last month"
        git push origin main